### PR TITLE
Add basic_dbeta_no_champ

### PR DESCRIPTION
**Pull request by Vghxv**
### Description

Part of #39 
Should be merged after directories are ignored #48 

### Implementation

Detail implementations are documented at the top of the notebook

### Required Hidden Data

Checked ones are the data required
```
./breast
├── champ_result
│   ├── GDC_breast_tissue
│   │   ├── DMP_result_0.csv
│   │   ├── DMP_result_1.csv
│   │   ├── all_beta_normalized_0.csv
│   │   └── all_beta_normalized_1.csv
│   ├── GSE148663
│   │   ├── DMP_result.csv
│   │   └── all_beta_normalized.csv
│   ├── GSE237036
│   │   ├── DMP_result.csv
│   │   └── all_beta_normalized.csv
│   ├── GSE243529
│   │   ├── DMP_result_0.csv
│   │   ├── DMP_result_1.csv
│   │   ├── all_beta_normalized_0.csv
│   │   └── all_beta_normalized_1.csv
│   └── GSE89093_nc
│       ├── all_beta_normalized.csv✅
│       └── phenotype.csv✅
├── data
│   ├── breast_0
│   │   └── sample_sheet.csv
│   └── breast_1
│       └── sample_sheet.csv
└── result
    └── GSE89093_nc
        └── train100
```
## Checklist

- [x] Detail implementation description at the top of notebook
- [x] Data input and output paths are correct
- [x] Free of spurious comments
- [x] Free of unnecessary notebook updates (e.g. cell executions count)

### CODE REVIEW

**Comment by xzh0623** [comment]
train_normal_avg = all_beta_normalized_normal.mean(skipna=True, axis=0)

計算dbeta的部分 這裡的axis=1，shape才會是(453627,)

**Comment by Vghxv** [comment]
之後在跑的時候不應該還在 debug

**Comment by Vghxv** [comment]
> 計算dbeta的部分 這裡的axis=1，shape才會是(453627,)
我在更上面的地方寫錯了

**Comment by Vghxv** [comment]
我要 push 計算結果嗎

**Comment by xzh0623** [comment]
> 我要 push 計算結果嗎

可以

**Comment by xzh0623** [comment]
all_beta_normalized_normal = all_beta_normalized_t.iloc[
    :, np.nonzero(mask.T)[1]
].T.reset_index(drop=True)
all_beta_normalized_tumor = all_beta_normalized_t.iloc[
    :, np.nonzero(~mask.T)[1]
].T.reset_index(drop=True)

在這個部分shape是(46, 453627)，後續在remove_outlier的時候會變成計算樣本的IQR

**Comment by Vghxv** [comment]
是，原本算的是錯的

**Comment by Vghxv** [comment]
image

套 outlier 的時候，每個 row 是samples

**Pull request merged**
